Revert an Unsaved Reminder
turingschool-projects/1610-remember-2 pull request #16
Opened 2017-02-14 22:05 UTC by adam-rice

@martensonbj @Tman22 @dylanavery720 

## Purpose

This feature allows the user to undo possible changes to a reminder while they are in the edit form, sending them back to the reminders route.

⛳️  fixes #12     🏌️ 

## Approach

We created an undo button on the edit form with an action 'rollbackChanges' on click. Then we created an action called rollbackChanges in the component dir that rolls back the attributes if the model has 'dirty attributes' and calls sendAction() to transition the user back to reminders.  

### Learning

We researched using the Ember Data API docs.

[property_hasDirtyAttributes](http://emberjs.com/api/data/classes/DS.Model.html#property_hasDirtyAttributes)

[method_rollbackAttributes](http://emberjs.com/api/data/classes/DS.Model.html#method_rollbackAttributes)

### Test coverage 

Our test runs through a scenario where a user creates a new reminder, then opens the edit form on that reminder, and lastly decides to select undo after adding a new title. The test checks that after all this the title is still the original. This test is passing. :martial_arts_uniform: 

### Follow-up tasks

- [Issue #13](https://github.com/turingschool-projects/1610-remember-2/issues/13)

### Screenshots

[After](http://imgur.com/GBsnm6V)

2017-02-14 22:17 UTC, martensonbj requested changes
Tiny button change

2017-02-14 22:17 UTC, martensonbj commented on app/templates/components/edit-reminder.hbs
> +  <button {{action 'rollbackChanges' model on='click'}} class='spec-edit-destroy-btn'>Undo</button>
Default button behavior is on=click - you can remove that

2017-02-14 22:17 UTC, martensonbj commented on app/templates/components/edit-reminder.hbs
> +  <button {{action 'rollbackChanges' model on='click'}} class='spec-edit-destroy-btn'>Undo</button>
Probably applies to other button's i've overlooked also

2017-02-15 02:27 UTC, adam-rice commented
@martensonbj  @dylanavery720 	343e65e

2017-02-15 03:39 UTC, Tman22 commented on tests/acceptance/reminder-list-test.js
> +
Will you assert the different urls?

2017-02-15 15:45 UTC, adam-rice commented
@martensonbj @Tman22 	7fcc4ef

2017-02-15 17:27 UTC, martensonbj approved these changes

2017-02-15 17:27 UTC, merged