Visual cues
turingschool-projects/1610-remember-2 pull request #17
Opened 2017-02-15 19:11 UTC by adam-rice

@martensonbj @Tman22 @dylanavery720 🐝 

## Purpose

The feature alerts the user that they must save their changes when using the edit form for a specific reminder.

❤️  fixes #13  💍  

## Approach

We created a new boolean when each reminder is created, edit set to false. On the edit hbs edit is switched to true and passed to the edit-reminder hbs. The edit-reminder hbs checks if edit is true and if so it renders the p tag 'You have unsaved changes!'.

### Learning

We learned how to add a new property to each reminder. Also, how to render an html element using the Ember if conditional {{if}}.

[Ember if conditional](https://guides.emberjs.com/v2.10.0/templates/conditionals/)

### Test coverage 

Our test is a scenario where the user adds and new reminder then clicks the edit on that specific reminder. Our test then checks to make sure that our visual cue is rendering.

### Follow-up tasks

- [Issue #14](https://github.com/turingschool-projects/1610-remember-2/issues/14)

### Screenshots

[After](http://imgur.com/PZynCXW)

2017-02-15 21:47 UTC, martensonbj requested changes

2017-02-15 21:47 UTC, martensonbj commented on app/templates/reminders/reminder/edit.hbs
> +{{edit-reminder model=model edit=true action='editReminder' action='rollbackChanges'}}
So right now it looks like you're triggering edit to be true as soon as you click the edit button. It makes more sense to have the indication pop up once you actually start changing a field (i.e. when there are dirty attributes). If a user hasn't actually made any changes they shouldn't be flagged to save unsaved changes.

2017-02-15 21:47 UTC, martensonbj commented on tests/acceptance/reminder-list-test.js
> +    assert.equal(currentURL(),'/reminders/1/edit');
See above comment but the `spec-edit-status` class should only be visible if a model has dirty attributes

2017-02-16 03:23 UTC, adam-rice commented
@martensonbj @Tman22 @dylanavery720 See five new commits for more improved visual cue to user regarding a reminder 🍯 being edited 🐝

2017-02-16 03:27 UTC, merged