Issue 2 - Adjust Root to Redirect to '/reminders'
turingschool-projects/1610-remember-2 pull request #5
Opened 2017-02-08 22:36 UTC by dylanavery720

@martensonbj @Tman22 @adam-rice 

## Purpose

[Link to Issue](https://github.com/turingschool-projects/1610-remember-2/issues/2)

User is redirected to '/reminders' path when visiting the '/' path of the Application.

Closes #2 :boxing_glove: 

## Approach

We used routing and 'transtitionTo', to make a redirect.

### Learning

We read the Ember docs regarding routing and redirecting with 'transtitionTo', and we used example syntax from the Ember docs.

### Test coverage 

Test were provided in boilerplate and tests are now passing after appropriate adjustments were made.

### Merge Dependencies and Related Work

_Link to merge dependency issues or PRs._

### Follow-up tasks

- [Issue #3](https://github.com/turingschool-projects/1610-remember-2/issues/3)

2017-02-08 22:59 UTC, martensonbj requested changes
Moooorrrre changes please

2017-02-08 22:59 UTC, martensonbj commented on app/models/reminder.js
> +  pinned: DS.attr('boolean', { defaultValue: false })
👍

2017-02-08 22:59 UTC, martensonbj commented on app/router.js
> +  this.route('reminders-list', { path: '/reminders' })
The route here should simply be 'reminders', the path should be '/'. This indicates that when the path matches '/',  ember will look for the `reminders` route which will hand it the model it needs to render.

2017-02-08 23:33 UTC, dylanavery720 commented
@martensonbj Hey! We made the requested change. Let us know if you need anything else before you merge. Thank you.  


 🍌    :gorilla:

2017-02-09 17:17 UTC, martensonbj commented
:shipit:

2017-02-09 17:17 UTC, merged